apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: bar-istio-system
  namespace: istio-system
spec:
  destination:
    name: bar
  route:
  - labels:
      version: v1
    weight: 100
  - labels:
      version: v2
    weight: 0